# Generated by Django 3.0.2 on 2020-03-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='citysss',
            field=models.CharField(default='abc', max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
