# Generated by Django 3.0.2 on 2020-03-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200328_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='citysss',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dob',
            field=models.DateField(),
        ),
    ]
